name: pytorch_example
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - auto_mix_prep==0.2.0
    - torch==1.11.0
    - torchvision==0.12.0
    - mlflow>=1.0
    - tensorboardX==2.5